### -*- coding: utf-8 -*- ##

DATABASE_ENGINE = 'postgresql_psycopg2'
DATABASE_NAME = '$POSTGRES_USER'
DATABASE_USER = '$POSTGRES_USER'
DATABASE_PASSWORD = '$POSTGRES_PASSWORD'
DATABASE_HOST = ''
DATABASE_PORT = '5432'
